/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

//<<<<<<< HEAD
import com.mysql.cj.xdevapi.Result;


//=======

//>>>>>>> 37b4fe7d690d186af95fbd9bced3b8ef439af891
import controleur.*;
import model.*;

/**
 *
 * @author BRICE
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form NewJFrame
     */
    public LoginFrame() {
        initComponents();
    }
    
    public static void lanceur() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
              LoginFrame frame =  new LoginFrame();
              frame.setVisible(true);
              frame.setLocationRelativeTo(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_principale = new javax.swing.JPanel();
        zonetext_pannel = new javax.swing.JPanel();
        titre_label = new javax.swing.JLabel();
        formulaire_pannel = new javax.swing.JPanel();
        mot_de_passe = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        mot_de_passe_Field = new javax.swing.JPasswordField();
        ENTRER = new javax.swing.JButton();
        EregistrerButton = new javax.swing.JButton();
        User_TextFIeld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        panel_principale.setLayout(new java.awt.BorderLayout());

        zonetext_pannel.setBackground(new java.awt.Color(255, 0, 0));

        titre_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        
        
        
        titre_label.setForeground(new java.awt.Color(255, 255, 255));
        titre_label.setText("Login Form");

        formulaire_pannel.setBackground(new java.awt.Color(51, 0, 51));
        formulaire_pannel.setMaximumSize(new java.awt.Dimension(2147, 2147));
        formulaire_pannel.setPreferredSize(new java.awt.Dimension(400, 400));
        formulaire_pannel.setLayout(new java.awt.GridBagLayout());

        mot_de_passe.setForeground(new java.awt.Color(255, 255, 255));
        mot_de_passe.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 68, 0, 0);
        formulaire_pannel.add(mot_de_passe, gridBagConstraints);

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("User_Name");
        username.setMaximumSize(new java.awt.Dimension(100, 100));
        username.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 68, 0, 0);
        formulaire_pannel.add(username, gridBagConstraints);

        mot_de_passe_Field.setText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 0, 44);
        formulaire_pannel.add(mot_de_passe_Field, gridBagConstraints);

        ENTRER.setBackground(new java.awt.Color(0, 51, 255));
        ENTRER.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ENTRER.setForeground(new java.awt.Color(255, 255, 255));
        ENTRER.setText("LOGIN");
        ENTRER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTRERActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 64, 0);
        formulaire_pannel.add(ENTRER, gridBagConstraints);

        EregistrerButton.setBackground(new java.awt.Color(255, 51, 0));
        EregistrerButton.setText("S'enregistrer");
        EregistrerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EregistrerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 64, 0);
        formulaire_pannel.add(EregistrerButton, gridBagConstraints);

        User_TextFIeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_TextFIeldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 18, 0, 44);
        formulaire_pannel.add(User_TextFIeld, gridBagConstraints);

        javax.swing.GroupLayout zonetext_pannelLayout = new javax.swing.GroupLayout(zonetext_pannel);
        zonetext_pannel.setLayout(zonetext_pannelLayout);
        zonetext_pannelLayout.setHorizontalGroup(
            zonetext_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonetext_pannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(formulaire_pannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        zonetext_pannelLayout.setVerticalGroup(
            zonetext_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonetext_pannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formulaire_pannel, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );

        panel_principale.add(zonetext_pannel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_TextFIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_TextFIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_TextFIeldActionPerformed

    private void EregistrerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EregistrerButtonActionPerformed
        dispose();
        Register register= new Register();
        register.setTitle("Login");
        register.setVisible(true);
        register.setLocationRelativeTo(null);
    }//GEN-LAST:event_EregistrerButtonActionPerformed

    private void ENTRERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTRERActionPerformed
        ConnexionBD con = new ConnexionBD();
		@SuppressWarnings("deprecation")
        String usrName = User_TextFIeld.getText().toString();
        String pwd = mot_de_passe_Field.getText().toString();
        System.out.println(usrName + " " + pwd);
		Authentification b =new Authentification(usrName, pwd );
		Authentification c=new Authentification();
		c= AthentificationBdController.infoLogin(AthentificationBdController.selectAuthentification());
		  boolean verif= b.equals(AthentificationBdController.infoLogin(AthentificationBdController.selectAuthentification()));
          System.out.println(c.getUser_name()+"\t"+c.getPwd());

        if(usrName.isEmpty() || pwd.isEmpty()){
            JOptionPane.showMessageDialog(this,"le nom d'utilisateur/le mot de passe ne doit pas etre vide!" ,"ERREUR", JOptionPane.ERROR_MESSAGE);
          
        }
 //comparaison des donnees de la bd et de la saisie
        else if(b.getUser_name().equals(c.getUser_name()) && b.getPwd().equals(c.getPwd())){
 //si cela est correct,on lance l'application
            dispose();
             Application App = new Application();
             App.setVisible(true);
             App.setLocationRelativeTo(null);
             
                
        }
        else {
          
            JOptionPane.showMessageDialog(this,"le nom d'utilisateur ou le mot de passe incorrect" ,"Ooops", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_ENTRERActionPerformed

    /**
     * @param args the command line arguments
     */
    public String Getnom(){
     return  mot_de_passe_Field.getText(); 
    }
     public String Getpassword(){
     return mot_de_passe_Field.getPassword().toString(); 
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENTRER;
    private javax.swing.JButton EregistrerButton;
    private javax.swing.JTextField User_TextFIeld;
    private javax.swing.JPanel formulaire_pannel;
    private javax.swing.JLabel mot_de_passe;
    private javax.swing.JPasswordField mot_de_passe_Field;
    private javax.swing.JPanel panel_principale;
    private javax.swing.JLabel titre_label;
    private javax.swing.JLabel username;
    private javax.swing.JPanel zonetext_pannel;
    // End of variables declaration//GEN-END:variables
}
