/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JOptionPane;

/**
 *
 * @author BRICE
 */
public class Register extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principale_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        formulaire_panel = new javax.swing.JPanel();
        prenomTextField = new javax.swing.JTextField();
        CNITextField_ = new javax.swing.JTextField();
        PasswordField1 = new javax.swing.JPasswordField();
        PasswordField2 = new javax.swing.JPasswordField();
        nonLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        ContactLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mot_de_passeLabel = new javax.swing.JLabel();
        mot_de_passeLabel2 = new javax.swing.JLabel();
        AccueilButton = new javax.swing.JButton();
        contactField = new javax.swing.JTextField();
        nomTextField = new javax.swing.JTextField();
        boutton_Enregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principale_panel.setBackground(new java.awt.Color(255, 0, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Formulaire d'enregistrement");

        javax.swing.GroupLayout principale_panelLayout = new javax.swing.GroupLayout(principale_panel);
        principale_panel.setLayout(principale_panelLayout);
        principale_panelLayout.setHorizontalGroup(
            principale_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principale_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        principale_panelLayout.setVerticalGroup(
            principale_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principale_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(principale_panel, java.awt.BorderLayout.PAGE_START);

        formulaire_panel.setBackground(new java.awt.Color(51, 0, 51));

        PasswordField1.setText("jPasswordField1");
        PasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField1ActionPerformed(evt);
            }
        });

        PasswordField2.setText("jPasswordField2");

        nonLabel.setForeground(new java.awt.Color(255, 255, 255));
        nonLabel.setText("NOM");

        prenomLabel.setForeground(new java.awt.Color(255, 255, 255));
        prenomLabel.setText("PRENOM");

        ContactLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactLabel.setText("CONTACT");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N` DE CNI");

        mot_de_passeLabel.setForeground(new java.awt.Color(255, 255, 255));
        mot_de_passeLabel.setText("Mot_de_passe");

        mot_de_passeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        mot_de_passeLabel2.setText("Mot_de_passe");

        AccueilButton.setText("Acueil");
        AccueilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilButtonActionPerformed(evt);
            }
        });

        boutton_Enregistrer.setText("Enregitrer");
        boutton_Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton_EnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formulaire_panelLayout = new javax.swing.GroupLayout(formulaire_panel);
        formulaire_panel.setLayout(formulaire_panelLayout);
        formulaire_panelLayout.setHorizontalGroup(
            formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formulaire_panelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(nonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(formulaire_panelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(prenomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(formulaire_panelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(ContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(formulaire_panelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(CNITextField_, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(formulaire_panelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(mot_de_passeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(formulaire_panelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(mot_de_passeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(PasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(formulaire_panelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(AccueilButton)
                .addGap(88, 88, 88)
                .addComponent(boutton_Enregistrer))
        );
        formulaire_panelLayout.setVerticalGroup(
            formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formulaire_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formulaire_panelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(prenomLabel))
                    .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formulaire_panelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ContactLabel))
                    .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formulaire_panelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(CNITextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formulaire_panelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(mot_de_passeLabel))
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formulaire_panelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(mot_de_passeLabel2))
                    .addComponent(PasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formulaire_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccueilButton)
                    .addComponent(boutton_Enregistrer)))
        );

        getContentPane().add(formulaire_panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField1ActionPerformed

             
             String nonTextFieldv = getnom();
             
             String PasswordField1v =  getPassword1();
             String PasswordField2v = getPassword2();
             
             if(nonTextFieldv .isEmpty() || PasswordField1v .isEmpty() || PasswordField2v.isEmpty()){
             JOptionPane.showMessageDialog(this,"veuillez remplir tous les champs" ,"ERREUR", JOptionPane.ERROR_MESSAGE); 
             }
             else{
              JOptionPane.showMessageDialog(this,"veuillez remplir tous les champs" ,"ERREUR", JOptionPane.ERROR_MESSAGE); }
    }//GEN-LAST:event_PasswordField1ActionPerformed

    public void tes(){
    System.out.println(getnom());
    }
    public String getnom(){
        return nomTextField.getText();
    }
     public String getPassword1(){
        return PasswordField1.getPassword().toString();
    }
      public String getPassword2(){
        return PasswordField2.getPassword().toString();
    }
       
    private void AccueilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilButtonActionPerformed
       dispose();
       LoginFrame login= new LoginFrame();
        login.setTitle("Login");
         login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_AccueilButtonActionPerformed

    private void boutton_EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton_EnregistrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutton_EnregistrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           Register regiter =new Register();
                 regiter.setVisible(true);
                 regiter.setLocationRelativeTo(null);
   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccueilButton;
    private javax.swing.JTextField CNITextField_;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JPasswordField PasswordField2;
    private javax.swing.JButton boutton_Enregistrer;
    private javax.swing.JTextField contactField;
    private javax.swing.JPanel formulaire_panel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mot_de_passeLabel;
    private javax.swing.JLabel mot_de_passeLabel2;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JLabel nonLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JTextField prenomTextField;
    private javax.swing.JPanel principale_panel;
    // End of variables declaration//GEN-END:variables
}
